name: 🔄 Rebuild log.html from all releases

on:
  workflow_dispatch:

jobs:
  rebuild-log:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install jsdom @octokit/rest

      - name: 🧠 Run changelog regeneration script
        run: node .github/scripts/updateChangelogFromReleases.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Commit & push updated log.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add log.html
          git commit -m "🔄 rebuild log.html from all releases"
          git push
